// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/academic/terms": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of all academic terms.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "academic"
                ],
                "summary": "List all academic terms",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AcademicTerm"
                            }
                        }
                    }
                }
            }
        },
        "/admin/analytics/attendance": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns overall attendance rate and status breakdown.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get attendance analytics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AttendanceAnalyticsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    }
                }
            }
        },
        "/admin/analytics/course-demand": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns analysis of course demand based on current enrollments and capacities.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get course demand analysis",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CourseDemandResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    }
                }
            }
        },
        "/admin/analytics/enrollment-trends": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns enrollment data over time (monthly) for the specified period.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get enrollment trends",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Period in months (default 12)",
                        "name": "months",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EnrollmentTrendsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    }
                }
            }
        },
        "/admin/analytics/professor-workload": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns workload stats for professors, including section counts and hours.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get professor workload analysis",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ProfessorWorkloadResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    }
                }
            }
        },
        "/admin/analytics/student-performance/{student_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a performance prediction for a specific student based on their GPA and historical data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Predict student performance",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student ID",
                        "name": "student_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StudentPerformancePrediction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    }
                }
            }
        },
        "/admin/dashboard/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns overview stats, enrollment status, grade distribution, GPA distribution, and section fill rates. Scoped by faculty or department if provided.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analytics"
                ],
                "summary": "Get dashboard statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by faculty ID",
                        "name": "faculty_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by department ID",
                        "name": "department_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DashboardStats"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    }
                }
            }
        },
        "/admin/students": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of all students.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all students",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new student user and profile.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create a new student",
                "parameters": [
                    {
                        "description": "Student details",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateStudentInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    }
                }
            }
        },
        "/admin/students/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns an Excel file containing the list of students.",
                "produces": [
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Export students to Excel",
                "responses": {
                    "200": {
                        "description": "Excel binary data",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/students/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a specific student by their ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get student by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the specified student's information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Update student details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated details",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateStudentInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft-deletes a student by their ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Delete a student",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/admin/students/{id}/transfer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Record a student transfer and update their current organization link.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Transfer a student to another faculty/department",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Transfer details",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.TransferStudentInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/admin/students/{id}/transfers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the history of organization transfers for a student.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get student transfer history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Student ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StudentDepartmentHistory"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate a user and return a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login and get a JWT token",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data: {token: \u003cjwt_token\u003e}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the profile of the user associated with the JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get the current authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Create a new user with the specified details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration details",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "data: {message: Registration successful}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apiutil.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apiutil.errorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "apiutil.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/apiutil.errorBody"
                }
            }
        },
        "handlers.CreateStudentInput": {
            "type": "object",
            "required": [
                "email",
                "faculty_id",
                "first_name",
                "last_name",
                "password"
            ],
            "properties": {
                "department_id": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "faculty_id": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "handlers.LoginInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handlers.RegisterInput": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "role": {
                    "$ref": "#/definitions/models.Role"
                }
            }
        },
        "handlers.TransferStudentInput": {
            "type": "object",
            "required": [
                "faculty_id"
            ],
            "properties": {
                "department_id": {
                    "type": "integer"
                },
                "faculty_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.UpdateStudentInput": {
            "type": "object",
            "required": [
                "faculty_id",
                "first_name",
                "last_name"
            ],
            "properties": {
                "department_id": {
                    "type": "integer"
                },
                "faculty_id": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "models.AcademicTerm": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "description": "e.g., \"Fall 2026\"",
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.AttendanceAnalyticsResponse": {
            "type": "object",
            "properties": {
                "by_status": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AttendanceStatusStat"
                    }
                },
                "overall_attendance_rate": {
                    "type": "number"
                }
            }
        },
        "models.AttendanceStatusStat": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "percentage": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.CourseDemand": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "course_id": {
                    "type": "integer"
                },
                "current_enrollments": {
                    "type": "integer"
                },
                "demand_level": {
                    "type": "string"
                },
                "fill_rate": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.CourseDemandResponse": {
            "type": "object",
            "properties": {
                "top_courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CourseDemand"
                    }
                }
            }
        },
        "models.DashboardStats": {
            "type": "object",
            "properties": {
                "enrollment_rates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SectionEnrollmentRate"
                    }
                },
                "enrollment_status": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "gpa_distribution": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "grade_distribution": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "overview": {
                    "$ref": "#/definitions/models.OverviewStats"
                }
            }
        },
        "models.EnrollmentTrend": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "integer"
                },
                "completed": {
                    "type": "integer"
                },
                "drop_rate": {
                    "type": "number"
                },
                "dropped": {
                    "type": "integer"
                },
                "month": {
                    "type": "string"
                },
                "total_enrollments": {
                    "type": "integer"
                }
            }
        },
        "models.EnrollmentTrendsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EnrollmentTrend"
                    }
                },
                "period": {
                    "type": "string"
                }
            }
        },
        "models.OverviewStats": {
            "type": "object",
            "properties": {
                "courses": {
                    "type": "integer"
                },
                "professors": {
                    "type": "integer"
                },
                "sections": {
                    "type": "integer"
                },
                "students": {
                    "type": "integer"
                }
            }
        },
        "models.ProfessorWorkload": {
            "type": "object",
            "properties": {
                "active_sections": {
                    "type": "integer"
                },
                "hours_per_week": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "professor_id": {
                    "type": "integer"
                },
                "rank": {
                    "type": "string"
                },
                "total_sections": {
                    "type": "integer"
                },
                "workload_level": {
                    "type": "string"
                }
            }
        },
        "models.ProfessorWorkloadResponse": {
            "type": "object",
            "properties": {
                "professors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProfessorWorkload"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/models.ProfessorWorkloadSummary"
                }
            }
        },
        "models.ProfessorWorkloadSummary": {
            "type": "object",
            "properties": {
                "average_hours": {
                    "type": "number"
                },
                "average_sections": {
                    "type": "number"
                },
                "total_professors": {
                    "type": "integer"
                }
            }
        },
        "models.Role": {
            "type": "string",
            "enum": [
                "admin",
                "employee",
                "professor",
                "student"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleEmployee",
                "RoleProfessor",
                "RoleStudent"
            ]
        },
        "models.SectionEnrollmentRate": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "course_code": {
                    "type": "string"
                },
                "course_name": {
                    "type": "string"
                },
                "fill_pct": {
                    "type": "number"
                },
                "filled": {
                    "type": "integer"
                },
                "section_id": {
                    "type": "integer"
                }
            }
        },
        "models.StudentDepartmentHistory": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "from_department_id": {
                    "type": "integer"
                },
                "from_faculty_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "student": {
                    "$ref": "#/definitions/models.User"
                },
                "student_id": {
                    "type": "integer"
                },
                "to_department_id": {
                    "type": "integer"
                },
                "to_faculty_id": {
                    "type": "integer"
                },
                "transferred_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.StudentPerformancePrediction": {
            "type": "object",
            "properties": {
                "average_score": {
                    "type": "number"
                },
                "confidence": {
                    "type": "integer"
                },
                "current_gpa": {
                    "type": "number"
                },
                "prediction": {
                    "type": "string"
                },
                "risk_level": {
                    "type": "string"
                },
                "trend": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "department_id": {
                    "type": "integer"
                },
                "department_transfers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.StudentDepartmentHistory"
                    }
                },
                "email": {
                    "type": "string"
                },
                "faculty_id": {
                    "type": "integer"
                },
                "first_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "national_id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/models.Role"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "UniOne API",
	Description:      "This is the UniOne Go backend server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
